# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArtistApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SVProgressHUD'
   pod 'ReachabilitySwift'
    pod 'Alamofire'
  # Pods for ArtistApp

  target 'ArtistAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArtistAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
